-- Emergency Check Queue Table
create table if not exists public.emergency_check_queue (
  id bigint generated by default as identity primary key,
  email text not null,
  metric_source text not null check (metric_source in ('realtime', 'aggregated')),
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  error_message text null,
  created_at timestamptz not null default now(),
  processed_at timestamptz null
);

create index if not exists emergency_queue_status_idx on public.emergency_check_queue(status);
create index if not exists emergency_queue_created_idx on public.emergency_check_queue(created_at desc);
create index if not exists emergency_queue_email_idx on public.emergency_check_queue(email);

-- Function to queue emergency check
create or replace function public.queue_emergency_check(p_email text, p_metric_source text)
returns void as $$
begin
  insert into public.emergency_check_queue (email, metric_source)
  values (p_email, p_metric_source)
  on conflict do nothing;
end;
$$ language plpgsql;

-- Trigger function for health_realtime inserts
create or replace function public.trigger_emergency_check_realtime()
returns trigger as $$
begin
  perform public.queue_emergency_check(new.email, 'realtime');
  return new;
end;
$$ language plpgsql;

-- Trigger function for health_aggregated inserts
create or replace function public.trigger_emergency_check_aggregated()
returns trigger as $$
begin
  perform public.queue_emergency_check(new.email, 'aggregated');
  return new;
end;
$$ language plpgsql;

-- Drop existing triggers if they exist
drop trigger if exists health_realtime_emergency_check on public.health_realtime;
drop trigger if exists health_aggregated_emergency_check on public.health_aggregated;

-- Create triggers on health_realtime
create trigger health_realtime_emergency_check
after insert on public.health_realtime
for each row
execute function public.trigger_emergency_check_realtime();

-- Create triggers on health_aggregated
create trigger health_aggregated_emergency_check
after insert on public.health_aggregated
for each row
execute function public.trigger_emergency_check_aggregated();
